//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismaGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrismaGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using a URI prefix other than localhost or 127.0.0.1, or a port below 1024 requires administrative privileges..
        /// </summary>
        internal static string AdminPrivilegesRequiredForPrefix {
            get {
                return ResourceManager.GetString("AdminPrivilegesRequiredForPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow PathInfo:.
        /// </summary>
        internal static string Allow_PathInfo_ {
            get {
                return ResourceManager.GetString("Allow PathInfo:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available.
        /// </summary>
        internal static string AnNewVersionIsAvailable {
            get {
                return ResourceManager.GetString("AnNewVersionIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        internal static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This provided configuration file is not accessible..
        /// </summary>
        internal static string CannotAccessConfigFile {
            get {
                return ResourceManager.GetString("CannotAccessConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access the config file!.
        /// </summary>
        internal static string CannotAccessConfigFileTitle {
            get {
                return ResourceManager.GetString("CannotAccessConfigFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute installer.
        /// </summary>
        internal static string CannotRunInstaller {
            get {
                return ResourceManager.GetString("CannotRunInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGI.
        /// </summary>
        internal static string CGI {
            get {
                return ResourceManager.GetString("CGI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGI applications.
        /// </summary>
        internal static string CGI_applications {
            get {
                return ResourceManager.GetString("CGI applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string Check_for_Updates {
            get {
                return ResourceManager.GetString("Check for Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear logs.
        /// </summary>
        internal static string Clear_logs {
            get {
                return ResourceManager.GetString("Clear logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file:.
        /// </summary>
        internal static string Configuration_file_ {
            get {
                return ResourceManager.GetString("Configuration file:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default documents.
        /// </summary>
        internal static string Default_documents {
            get {
                return ResourceManager.GetString("Default documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name.
        /// </summary>
        internal static string Document_name {
            get {
                return ResourceManager.GetString("Document name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document root:.
        /// </summary>
        internal static string Document_root_ {
            get {
                return ResourceManager.GetString("Document root:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download the new version manually instead..
        /// </summary>
        internal static string DownloadNewVersionManually {
            get {
                return ResourceManager.GetString("DownloadNewVersionManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variables.
        /// </summary>
        internal static string Environment_variables {
            get {
                return ResourceManager.GetString("Environment variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Projects.
        /// </summary>
        internal static string External_Projects {
            get {
                return ResourceManager.GetString("External Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the server.
        /// </summary>
        internal static string FailedToStartServer {
            get {
                return ResourceManager.GetString("FailedToStartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastCGI applications.
        /// </summary>
        internal static string FastCGI_applications {
            get {
                return ResourceManager.GetString("FastCGI applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred.
        /// </summary>
        internal static string InternalErrorOccurred {
            get {
                return ResourceManager.GetString("InternalErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string InternalErrorTitle {
            get {
                return ResourceManager.GetString("InternalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid config file!.
        /// </summary>
        internal static string InvalidConfigFileTitle {
            get {
                return ResourceManager.GetString("InvalidConfigFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port numbers must be in the range of 0 to 65535..
        /// </summary>
        internal static string InvalidPortNumber {
            get {
                return ResourceManager.GetString("InvalidPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefixes must start with http:// or https:// and end with a slash..
        /// </summary>
        internal static string InvalidPrefix {
            get {
                return ResourceManager.GetString("InvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke on extension.
        /// </summary>
        internal static string Invoke_on_extension {
            get {
                return ResourceManager.GetString("Invoke on extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke on path.
        /// </summary>
        internal static string Invoke_on_path {
            get {
                return ResourceManager.GetString("Invoke on path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener prefixes.
        /// </summary>
        internal static string Listener_prefixes {
            get {
                return ResourceManager.GetString("Listener prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load configuration file.
        /// </summary>
        internal static string Load_configuration_file {
            get {
                return ResourceManager.GetString("Load configuration file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log as JSON:.
        /// </summary>
        internal static string Log_as_JSON_ {
            get {
                return ResourceManager.GetString("Log as JSON:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file:.
        /// </summary>
        internal static string Log_file_ {
            get {
                return ResourceManager.GetString("Log file:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level:.
        /// </summary>
        internal static string Log_level_ {
            get {
                return ResourceManager.GetString("Log level:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file.
        /// </summary>
        internal static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisma web server ({0}).
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisma version {0} is available!.
        /// </summary>
        internal static string NewVersionHeader {
            get {
                return ResourceManager.GetString("NewVersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available. Use the buttons below to download and install the new version, or view it online..
        /// </summary>
        internal static string NewVersionText {
            get {
                return ResourceManager.GetString("NewVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no configuration loaded.
        /// </summary>
        internal static string NoConfigurationLoaded {
            get {
                return ResourceManager.GetString("NoConfigurationLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not serving.
        /// </summary>
        internal static string NotServing {
            get {
                return ResourceManager.GetString("NotServing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        internal static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string Port_ {
            get {
                return ResourceManager.GetString("Port:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A port and/or prefix is already in use by another process.
        /// </summary>
        internal static string PortOrPrefixAlreadyInUse {
            get {
                return ResourceManager.GetString("PortOrPrefixAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisma configuration files.
        /// </summary>
        internal static string PrismaConfigurationFiles {
            get {
                return ResourceManager.GetString("PrismaConfigurationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisma web server.
        /// </summary>
        internal static string PrismaWebServer {
            get {
                return ResourceManager.GetString("PrismaWebServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the path to a file..
        /// </summary>
        internal static string ProvidePathToFile {
            get {
                return ResourceManager.GetString("ProvidePathToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid directory..
        /// </summary>
        internal static string ProvideValidDirectory {
            get {
                return ResourceManager.GetString("ProvideValidDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid path to a file..
        /// </summary>
        internal static string ProvideValidLogFile {
            get {
                return ResourceManager.GetString("ProvideValidLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewrite rules.
        /// </summary>
        internal static string Rewrite_rules {
            get {
                return ResourceManager.GetString("Rewrite rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewrite to.
        /// </summary>
        internal static string Rewrite_to {
            get {
                return ResourceManager.GetString("Rewrite to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        internal static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string Save_As {
            get {
                return ResourceManager.GetString("Save As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select document root.
        /// </summary>
        internal static string Select_document_root {
            get {
                return ResourceManager.GetString("Select document root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select log file.
        /// </summary>
        internal static string Select_log_file {
            get {
                return ResourceManager.GetString("Select log file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving at {0}.
        /// </summary>
        internal static string ServingAt {
            get {
                return ResourceManager.GetString("ServingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket.
        /// </summary>
        internal static string Socket {
            get {
                return ResourceManager.GetString("Socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start serving.
        /// </summary>
        internal static string StartServing {
            get {
                return ResourceManager.GetString("StartServing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop serving.
        /// </summary>
        internal static string StopServing {
            get {
                return ResourceManager.GetString("StopServing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now.
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the new version online.
        /// </summary>
        internal static string VisitWebsite {
            get {
                return ResourceManager.GetString("VisitWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version..
        /// </summary>
        internal static string YouHaveTheLatestVersion {
            get {
                return ResourceManager.GetString("YouHaveTheLatestVersion", resourceCulture);
            }
        }
    }
}
